data:
  dataloader: {batch_size: 36, class_balance: true, data_workers: 3}
  dataset: {n_share: 25, n_total: 65, name: officehome, root_path: /root/autodl-tmp/office_caltech_10,
    source: 1, target: 0}
log: {log_interval: 10, root_dir: /root/BCD_PDA/Caltech_log/1_to_0/Source_Discri_0}
misc: {gpus: 1}
model: {base_model: resnet50, pretrained_model: /root/BCD_PDA/resnet50-19c8e357.pth}
test: {resume_file: Clipart_to_Art.pkl, test_interval: 500, test_only: false}
train: {adv_loss_aug_tradeoff: 10.0, adv_loss_tradeoff: 1.0, ce_aug_tradeoff: 1.0,
  entropy_tradeoff: 0.2, lr: 0.001, min_step: 20000, momentum: 0.9, weight_decay: 0.0005}

