data:  # office 31 配置
 dataloader: {batch_size: 12, class_balance: true, data_workers: 0} # 可以改成ETN的batchszie=36
 dataset: {n_share: 10, n_total: 31, name: office31, root_path: /root/autodl-tmp/office31,
   source: 2, target: 0}
log: {log_interval: 100, root_dir: /root/BCD_PDA/log}
misc: {gpus: 0}
model: {base_model: resnet50, pretrained_model: /root/BCD_PDA/resnet50-19c8e357.pth}
test: {resume_file: best.pkl, test_interval: 20, test_only: False}
train: {Grass_lambda: 5000, adv_loss_tradeoff: 1.0, PLGE_lambda_L2: 10, c1_loss: 0.2, PLGE_lambda_L1: 1.0, ce_aug_tradeoff: 1.0, #office 31
       lr: 0.001,entropy_tradeoff: 0.1, min_step: 5000, momentum: 0.9, weight_decay: 0.0005, adv_loss_aug_tradeoff: 1.0, Source_Discri: 1.0} # 0.001 #跑5000次